#!/usr/bin/env python3
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4

import argparse, csv, logging, os, sys
from datetime import datetime, timedelta, timezone

def converttostring(listorstring):
    return ''.join(listorstring)
    
parser = argparse.ArgumentParser(description="Listing st-procras tasks included in a file.")

DEFAULTFILE = os.environ['HOME'] + "/.stprocras-events"

parser.add_argument("-f", "--file", default=DEFAULTFILE, help="Flat tab-separated values file to read from, overriding the default dotfile in home directory.")

args = parser.parse_args()

firstcolumnname = "name"
secondcolumnname = "isodt"
columnnames = [firstcolumnname, secondcolumnname]

try:
    with open(converttostring(args.file), 'r', newline='') as dsvfile:
        reader = csv.DictReader(dsvfile, columnnames, delimiter='\t')
        for row in reader:
            try:
                dtwhen = datetime.strptime(row[secondcolumnname], "%Y-%m-%dT%H:%M:%S%z")
            except (ValueError, TypeError) as e:
                logging.warning(sys.argv[0] + ": Date in line " + str(reader.line_num) + " does not adhere to format. Skipping.")
                continue

            utc_dtnow = datetime.now(timezone.utc)
            dtnow = utc_dtnow.astimezone()

            delta = dtwhen - dtnow

            if delta.days > 0:
                print(row['name'] + " - " + str(delta.days) + " days left", end='')
            elif delta.days == 0:
                delta_sec = int(delta.total_seconds())

                delta_hour = delta_sec // 3600
                delta_sec -= delta_hour * 3600

                delta_min = delta_sec // 60
                delta_sec -= delta_min * 60

                print(row['name'] + " - " + str(delta_hour) + " hours, " + str(delta_min) + " minutes, " + str(delta_sec) + " seconds left", end='')
            elif delta.days < 0:
                print("\u001b[41;1m\u001b[37m" + row['name'] + " - " + str(abs(delta.days)) + " days past", end='')

            print("\u001b[0m")
except FileNotFoundError as e:
    logging.critical(sys.argv[0] + " FileNotFoundError: default or provided database does not exist.")
    exit()
