#!/usr/bin/env python3
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4

import argparse, csv, logging, os, sys

parser = argparse.ArgumentParser(description="Removing certain rows of a st-procras file, based on the input")

DEFAULTFILE = os.environ['HOME'] + "/.stprocras-events"

parser.add_argument("-f", "--file", default=DEFAULTFILE, help="Flat tab-separated values file to read from and write to, overriding the default dotfile in home directory.")
parser.add_argument('integers', metavar='rowNumber', type=int, nargs='+', help="Row numbers to be deleted.")

args = parser.parse_args()

firstcolumnname = "name"
secondcolumnname = "isodt"
columnnames = [firstcolumnname, secondcolumnname]

try:
    with open(converttostring(args.file), 'r+', newline='') as dsvfile:
        pass # TODO Replace this with body of function
        # To avoid buffer overflows from a file too large, write to another
        # temporary file on disk, then replace the old file with the new one.
except FileNotFoundError as e:
    logging.critical(sys.argv[0] + " FileNotFoundError: default or provided database does not exist.")
    exit()

